### ISSUE TITLE
NON-GDI processors do not function

### ISSUE THREAD

**Issue by JernejL** [ikkentim/SanMap#2]
Only GDI processor actually does anything, imagemagick 32 and 64 bit do nothing at all - is there need for any specific set-up?

**Comment by ikkentim** [comment]
It doesn't require anything special, it _should_ work out of the box...

**Comment by ikkentim** [comment]
It doesn't work for me either,, looking into it...

**Comment by ikkentim** [comment]
Fixing...

**Comment by ikkentim** [comment]
Could you try v1.5?
https://github.com/ikkentim/SanMap/releases/tag/v1.5

**Comment by ikkentim** [comment]
@JernejL does this fix your problem?

**Comment by JernejL** [comment]
Yes, 1.5 works!
