### ISSUE TITLE
google maps api no longer free

### ISSUE THREAD

**Issue by FatCatTuxedo** [ikkentim/SanMap#4]
Are you able to remake this for mapbox?

https://docs.mapbox.com/help/tutorials/google-to-mapbox/

**Comment by FatCatTuxedo** [comment]
@ikkentim

**Comment by ikkentim** [comment]
I’m on vacation, will see when back

**Comment by ikkentim** [comment]
But also, unless you get crazy traffic, all you have to do is get an api key from the google console and then it’s still free.

**Comment by FatCatTuxedo** [comment]
@ikkentim its not free anymore at all though.

Running this on a server with more than 10 players will hit the limit.

**Comment by ikkentim** [comment]
I haven't been able to find time/motivation to make this happen. If anyone wants it, it doesn't seem too difficult. They can make it for themselves or open a PR.
